# Generated by Django 3.2 on 2021-06-03 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=100)),
                ('RegNo', models.IntegerField(max_length=20)),
                ('CGPA', models.FloatField()),
            ],
        ),
    ]
